# Generated by Django 2.1.1 on 2019-11-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsumg',
            name='other',
            field=models.TextField(default=None),
        ),
    ]
