# Generated by Django 2.1.1 on 2019-12-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20191114_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Samsumg',
            new_name='Samsung',
        ),
    ]
